### ISSUE TITLE
URLs not working as expected

### ISSUE THREAD

**Issue by JustinBusschau** [Workable/confluence-docs-as-code#27]
According to the [features](https://github.com/Workable/confluence-docs-as-code?tab=readme-ov-file#features) this workflow **Converts internal links to Confluence links** - but I've not been able to get this to work.

**Example:**
In MkDocs, I have an "executive summary" in my `docs` folder which links to a glossary to explain some of the terms I use in the document.

The folder structure looks a little like this:
```
.
└─ docs
  ├─ executive-summary.md
  └─ glossary.md
```

In my `executive-summary` I have links similar to this:

`executive-summary.md`
```
- We have some code in [GitHub](https://github.com/).
- We also use [CI/CD](/glossary/) - so we're very proud of ourselves.
```

In the MkDocs local preview (using `mkdocs serve`) both the links to GitHub and to our glossary work as expected.

Once the docs are uploaded to Confluence, the links where I provide a full URL work as expected, but the relative links to other documents (e.g. my link to the glossary) don't work.

The `/glossary/` link is rendered as `https://my-organization.atlassian.net/glossary/`.

Can anyone tell me what I'm doing wrong here?

**Comment by echetzakis** [comment]
Hi @JustinBusschau try referencing your glossary page like this:
```
- We also use [CI/CD](glossary.md) - so we're very proud of ourselves.
```

**Comment by JustinBusschau** [comment]
The problem I have with this is that it not only breaks my local workflow, but also doesn't correct the problem on Confluence.

With the content of `executive-summary.md` changed to:
```
- We also use [CI/CD](/glossary/) - so we're very proud of ourselves.
```

When I run `mkdocs serve`, open ` http://127.0.0.1:8000/executive-summary/` and click on the `CI/CD` hyperlink, I get a 404 in the browser and in the stdout I see:
```
INFO    -  [12:34:56] Browser connected: http://127.0.0.1:8000/executive-summary/
WARNING -  [12:35:01] "GET /glossary.md HTTP/1.1" code 404
```

I tried uploading to Confluence anyway and the same issue persists - links are not redirecting to the correct page. The glossary page, once published to Confluence, is available via `https://m{organization}.atlassian.net/wiki/spaces/{space-id}/pages/{page-id}/Glossary` but the hyperlink in my `executive-summary` page redirects to `https://{organization}.atlassian.net/Glossary`

Any advice?

**Comment by JustinBusschau** [comment]
Never mind me ... turns out my habit of always adding the leading `/` for files in the root folder is what was tripping me up.

The suggested solution works well, but not exactly as I wanted.

With the content of `executive-summary.md` changed to:
```
- We also use [CI/CD](glossary.md) - so we're very proud of ourselves.
```

I get the expected result on `http://127.0.0.1:8000/executive-summary/` but the hyperlinked text is changed from **CI/CD** to **Glossary** on Confluence - which does mess with the text flow, meaning I have had to change to use this instead so that I can keep my local view when editing consistent with the Confluence rendering:
```
- We also use **CI/CD** ([Glossary](glossary.md)) - so we're very proud of ourselves.
```
